//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data.ORTF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_parameters_data
    {
        public string parameter_name { get; set; }
        public string PharmacyTeamERPCode { get; set; }
        public string PharmacyERPCode { get; set; }
        public string PharmacistERPCode { get; set; }
        public string PhysicianERPCode { get; set; }
        public string DrugERPCode { get; set; }
        public string SecondPhysicianERPCode { get; set; }
        public string PrimaryInsuranceERPCode { get; set; }
        public string SecondaryInsuranceERPCode { get; set; }
        public string PatientInsuranceERPCode { get; set; }
        public string SecondaryPatientInsuranceERPCode { get; set; }
        public string PatientERPCode { get; set; }
        public string PatientShipERPCode { get; set; }
        public string RosterERPCode { get; set; }
        public string RecordLinksERPCode { get; set; }
        public string PatientDiagnosisCodeERPCode1 { get; set; }
        public string PatientDiagnosisCodeERPCode2 { get; set; }
        public string PatientDiagnosisCodeERPCode3 { get; set; }
        public string PatientDiagnosisCodeERPCode4 { get; set; }
        public string OrderERPCode { get; set; }
        public string PriorAuthorizationERPCode { get; set; }
        public string PronotesERPCode { get; set; }
        public string PrescriptionERPCode { get; set; }
        public string PrescriptionNumber { get; set; }
        public string BusinessName { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientAddressLine1 { get; set; }
        public string PatientCity { get; set; }
        public string PatientState { get; set; }
        public string PatientPostalCode { get; set; }
        public string PatientPhoneNumber { get; set; }
        public string PatientCounty { get; set; }
        public string PatientDOB { get; set; }
        public string PatientSocialSecurityNumber { get; set; }
        public string PatientGender { get; set; }
        public string PatientLanguage { get; set; }
        public string PatientRoute { get; set; }
        public string PatientReferralDate { get; set; }
        public string PatientHeight { get; set; }
        public string PatientWeight { get; set; }
        public string PatientAllergies { get; set; }
        public string PatientStartOfCareDate { get; set; }
        public string PatientPrimaryDiagnosisCode { get; set; }
        public string PatientSecondaryDiagnosisCode { get; set; }
        public string PatientTerciaryDiagnosisCode { get; set; }
        public string PatientQuaternaryDiagnosisCode { get; set; }
        public string PatientMaritalStatus { get; set; }
        public string PatientDeliveryInstruction { get; set; }
        public string PatientStatus { get; set; }
        public string PatientDriverLicense { get; set; }
        public string PharmacySiteNumber { get; set; }
        public string PatientOtherAllergies { get; set; }
        public string PatientWorkPhoneNumber { get; set; }
        public string PatientCellPhoneNumber { get; set; }
        public string PatientEmail { get; set; }
        public string PatientShippingName { get; set; }
        public string PatientShippingAttention { get; set; }
        public string PatientShippingAddress { get; set; }
        public string PatientShippingCity { get; set; }
        public string PatientShippingState { get; set; }
        public string PatientShippingPostalCode { get; set; }
        public string PatientShippingPhoneNumber { get; set; }
        public string PatientShippingType { get; set; }
        public string PatienthippingExpectedDeliveryDate { get; set; }
        public string PatientOtherContactLastName { get; set; }
        public string PatientOtherContactFirstName { get; set; }
        public string PatientContactRelationship { get; set; }
        public string PatientOtherContactAddress { get; set; }
        public string PatientOtherContactHomePhoneNumber { get; set; }
        public string PatientOtherContactWorkPhoneNumber { get; set; }
        public string PatientOtherContactCellPhoneNumber { get; set; }
        public string PatientOtherContactCity { get; set; }
        public string PatientOtherContactState { get; set; }
        public string PatientOtherContactZip { get; set; }
        public string PatientOtherContactType { get; set; }
        public string PatientOtherContactEmailAddress { get; set; }
        public string PatientOtherContactWorkPhoneExtension { get; set; }
        public string PrimaryInsuranceEffectiveDate { get; set; }
        public string PrimaryInsurancePolicyNumber { get; set; }
        public string PrimaryInsuranceGroupNumber { get; set; }
        public string PrimaryInsuredName { get; set; }
        public string PrimaryInsuredEmployerName { get; set; }
        public string SecondaryInsuranceEffectiveDate { get; set; }
        public string SecondaryInsurancePolicyNumber { get; set; }
        public string SecondaryInsuranceGroupNumber { get; set; }
        public string SecondaryInsuredName { get; set; }
        public string SecondaryInsuredEmployerName { get; set; }
        public string OrderStatus { get; set; }
        public string OrderDescription { get; set; }
        public string OrderedDate { get; set; }
        public string OrderStartDate { get; set; }
        public string OrderStopDate { get; set; }
        public string DrugStrength { get; set; }
        public string DrugStrengthUnit { get; set; }
        public string DrugFrequency { get; set; }
        public string OriginalPrescriptionNumber { get; set; }
        public string OrderClass { get; set; }
        public string OrderAcceptedFlag { get; set; }
        public string OrderFrequentType { get; set; }
        public string RefillsRemaining { get; set; }
        public string PriorAuthorizationReferenceNumber { get; set; }
        public string PriorAuthorizationStartDate { get; set; }
        public string PriorAuthorizationStopDate { get; set; }
        public string PriorAuthorizationNumber { get; set; }
        public string PriorAuthorizedPriceToUse { get; set; }
        public string PriorAuthorizedLimit { get; set; }
        public string PriorAuthorizationPeriod { get; set; }
        public string PriorAuthorizationType { get; set; }
        public string PriorAuthorizationInstruction { get; set; }
        public string PriorAuthorizationRenewalNumber { get; set; }
        public string PharmacistName { get; set; }
        public string ProgressNoteDate { get; set; }
        public string SendingPharmacyName { get; set; }
        public string SendingPharmacistName { get; set; }
        public string SendingPharmacyNPI { get; set; }
        public string SendingPharmacyPhoneNumber { get; set; }
        public string SendingPharmacyAddressLine1 { get; set; }
        public string SendingPharmacyAddressLine2 { get; set; }
        public string SendingPharmacyCity { get; set; }
        public string SendingPharmacyState { get; set; }
        public string SendingPharmacyZip { get; set; }
        public string OriginalRxNumber { get; set; }
        public string ReceivingPharmacyName { get; set; }
        public string ReceivingPharmacistName { get; set; }
        public string ReceivingPharmacyNPI { get; set; }
        public string ReceivingPharmacyPhoneNumber { get; set; }
        public string ReceivingPharmacyAddressLine1 { get; set; }
        public string ReceivingPharmacyAddressLine2 { get; set; }
        public string ReceivingPharmacyCity { get; set; }
        public string ReceivingPharmacyState { get; set; }
        public string ReceivingPharmacyZip { get; set; }
        public string PrescriptionDoctorName { get; set; }
        public string PrescriptionDoctorNPI { get; set; }
        public string OriginalDispensedQuantity { get; set; }
        public string PrescriptionExpirationDate { get; set; }
        public string PrescriptionDirections { get; set; }
        public string PrescriptionInstruction { get; set; }
        public string PrescriptionSupplyDays { get; set; }
        public string PrescrptionDays { get; set; }
        public string LastFillDate { get; set; }
        public string OriginalPrescriptionDate { get; set; }
        public string PrescriptionNumberOfLabel { get; set; }
        public string RXOrigin { get; set; }
        public string PrescriptionRefillAuthorizationStatus { get; set; }
        public string PrescriptionFillType { get; set; }
        public Nullable<int> record_id { get; set; }
        public string ReturnMessage { get; set; }
        public long sp_parameters_dataId { get; set; }
    }
}
