using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhysicianPortal.Web.Models
{
    public class RefFormTransplantViewModel : ReferralFormBaseViewModel
    {
        public int RefFormTransplantId { get; set; }
        public bool ChkBox_Z94_0Kidney { get; set; }
        public bool ChkBox_Z94_83Pancreas { get; set; }
        public System.DateTime DateofTransplant { get; set; }
        public bool ChkBox_Z94_4Liver { get; set; }
        public bool ChkBox_Z94_82Intestine { get; set; }
        public bool ChkBox_Spanish { get; set; }
        public bool ChkBox_English { get; set; }
        public double Height_TxtBox { get; set; }
        public double Weight_TxtBox { get; set; }
        public string Allergies_TxtBox { get; set; }
        public bool ChkBox_NKDA { get; set; }
        public string Medication_TxtBox1 { get; set; }
        public string DIRECTIONS_TextBox1 { get; set; }
        public string Qty_TxtBox1 { get; set; }
        public string DNS_TxtBox1 { get; set; }
        public string REFILLS_TxtBox1 { get; set; }
        public string Medication_TxtBox2 { get; set; }
        public string DIRECTIONS_TextBox2 { get; set; }
        public string Qty_TxtBox2 { get; set; }
        public string DNS_TxtBox2 { get; set; }
        public string REFILLS_TxtBox2 { get; set; }
        public string Medication_TxtBox3 { get; set; }
        public string DIRECTIONS_TextBox3 { get; set; }
        public string Qty_TxtBox3 { get; set; }
        public string DNS_TxtBox3 { get; set; }
        public string REFILLS_TxtBox3 { get; set; }
        public string Medication_TxtBox4 { get; set; }
        public string DIRECTIONS_TextBox4 { get; set; }
        public string Qty_TxtBox4 { get; set; }
        public string DNS_TxtBox4 { get; set; }
        public string REFILLS_TxtBox4 { get; set; }
        public string Medication_TxtBox5 { get; set; }
        public string DIRECTIONS_TextBox5 { get; set; }
        public string Qty_TxtBox5 { get; set; }
        public string DNS_TxtBox5 { get; set; }
        public string REFILLS_TxtBox5 { get; set; }
        public string Medication_TxtBox6 { get; set; }
        public string DIRECTIONS_TextBox6 { get; set; }
        public string Qty_TxtBox6 { get; set; }
        public string DNS_TxtBox6 { get; set; }
        public string REFILLS_TxtBox6 { get; set; }
        public string Medication_TxtBox7 { get; set; }
        public string DIRECTIONS_TextBox7 { get; set; }
        public string Qty_TxtBox7 { get; set; }
        public string DNS_TxtBox7 { get; set; }
        public string REFILLS_TxtBox7 { get; set; }
        public string Medication_TxtBox8 { get; set; }
        public string DIRECTIONS_TextBox8 { get; set; }
        public string Qty_TxtBox8 { get; set; }
        public string DNS_TxtBox8 { get; set; }
        public string REFILLS_TxtBox8 { get; set; }
        public string Medication_TxtBox9 { get; set; }
        public string DIRECTIONS_TextBox9 { get; set; }
        public string Qty_TxtBox9 { get; set; }
        public string DNS_TxtBox9 { get; set; }
        public string REFILLS_TxtBox9 { get; set; }
        public string Medication_TxtBox10 { get; set; }
        public string DIRECTIONS_TextBox10 { get; set; }
        public string Qty_TxtBox10 { get; set; }
        public string DNS_TxtBox10 { get; set; }
        public string REFILLS_TxtBox10 { get; set; }
        public string Medication_TxtBox11 { get; set; }
        public string DIRECTIONS_TextBox11 { get; set; }
        public string Qty_TxtBox11 { get; set; }
        public string DNS_TxtBox11 { get; set; }
        public string REFILLS_TxtBox11 { get; set; }
        public string Medication_TxtBox12 { get; set; }
        public string DIRECTIONS_TextBox12 { get; set; }
        public string Qty_TxtBox12 { get; set; }
        public string DNS_TxtBox12 { get; set; }
        public string REFILLS_TxtBox12 { get; set; }
        public string Medication_TxtBox13 { get; set; }
        public string DIRECTIONS_TextBox13 { get; set; }
        public string Qty_TxtBox13 { get; set; }
        public string DNS_TxtBox13 { get; set; }
        public string REFILLS_TxtBox13 { get; set; }
        public string Medication_TxtBox14 { get; set; }
        public string DIRECTIONS_TextBox14 { get; set; }
        public string Qty_TxtBox14 { get; set; }
        public string DNS_TxtBox14 { get; set; }
        public string REFILLS_TxtBox14 { get; set; }
        public string Medication_TxtBox15 { get; set; }
        public string DIRECTIONS_TextBox15 { get; set; }
        public string Qty_TxtBox15 { get; set; }
        public string DNS_TxtBox15 { get; set; }
        public string REFILLS_TxtBox15 { get; set; }
        public string Medication_TxtBox16 { get; set; }
        public string DIRECTIONS_TextBox16 { get; set; }
        public string Qty_TxtBox16 { get; set; }
        public string DNS_TxtBox16 { get; set; }
        public string REFILLS_TxtBox16 { get; set; }
        public string Medication_TxtBox17 { get; set; }
        public string DIRECTIONS_TextBox17 { get; set; }
        public string Qty_TxtBox17 { get; set; }
        public string DNS_TxtBox17 { get; set; }
        public string REFILLS_TxtBox17 { get; set; }
        public string Medication_TxtBox18 { get; set; }
        public string DIRECTIONS_TextBox18 { get; set; }
        public string Qty_TxtBox18 { get; set; }
        public string DNS_TxtBox18 { get; set; }
        public string REFILLS_TxtBox18 { get; set; }
        public string Medication_TxtBox19 { get; set; }
        public string DIRECTIONS_TextBox19 { get; set; }
        public string Qty_TxtBox19 { get; set; }
        public string DNS_TxtBox19 { get; set; }
        public string REFILLS_TxtBox19 { get; set; }
        public string Medication_TxtBox20 { get; set; }
        public string DIRECTIONS_TextBox20 { get; set; }
        public string Qty_TxtBox20 { get; set; }
        public string DNS_TxtBox20 { get; set; }
        public string REFILLS_TxtBox20 { get; set; }
        public string Medication_TxtBox21 { get; set; }
        public string DIRECTIONS_TextBox21 { get; set; }
        public string Qty_TxtBox21 { get; set; }
        public string DNS_TxtBox21 { get; set; }
        public string REFILLS_TxtBox21 { get; set; }
        public string Medication_TxtBox22 { get; set; }
        public string DIRECTIONS_TextBox22 { get; set; }
        public string Qty_TxtBox22 { get; set; }
        public string DNS_TxtBox22 { get; set; }
        public string REFILLS_TxtBox22 { get; set; }
        public string Medication_TxtBox23 { get; set; }
        public string DIRECTIONS_TextBox23 { get; set; }
        public string Qty_TxtBox23 { get; set; }
        public string DNS_TxtBox23 { get; set; }
        public string REFILLS_TxtBox23 { get; set; }
        public string Medication_TxtBox24 { get; set; }
        public string DIRECTIONS_TextBox24 { get; set; }
        public string Qty_TxtBox24 { get; set; }
        public string DNS_TxtBox24 { get; set; }
        public string REFILLS_TxtBox24 { get; set; }
        public string Medication_TxtBox25 { get; set; }
        public string DIRECTIONS_TextBox25 { get; set; }
        public string Qty_TxtBox25 { get; set; }
        public string DNS_TxtBox25 { get; set; }
        public string REFILLS_TxtBox25 { get; set; }
        public bool ChkBox_MD1 { get; set; }
        public string MD1_TxtBox { get; set; }
        public bool ChkBox_MD2 { get; set; }
        public string MD2_TxtBox { get; set; }
        public bool ChkBox_MD3 { get; set; }
        public string MD3_TxtBox { get; set; }
        public bool ChkBox_MD4 { get; set; }
        public string MD4_TxtBox { get; set; }
        public bool ChkBox_MD5 { get; set; }
        public string MD5_TxtBox { get; set; }
        public bool ChkBox_MD6 { get; set; }
        public string MD6_TxtBox { get; set; }
        public bool Person1_ChkBox { get; set; }
        public string Person1_Contact_TxtBox { get; set; }
        public bool Person2_ChkBox { get; set; }
        public string Person2_Contact_TxtBox { get; set; }
        public bool Person3_ChkBox { get; set; }
        public string Person3_Contact_TxtBox { get; set; }
        public string Medication_TxtBox26 { get; set; }
        public string DIRECTIONS_TextBox26 { get; set; }
        public string Qty_TxtBox26 { get; set; }
        public string DNS_TxtBox26 { get; set; }
        public string REFILLS_TxtBox26 { get; set; }
        public bool ChkBox_Z94_1 { get; set; }
        public bool ChkBox_ZZ94_2 { get; set; }
    }
}