using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhysicianPortal.Web.Models
{
    public class RefFormRheumatologyViewModel : ReferralFormBaseViewModel
    {
        public int RefFormRheumatologyId { get; set; }
        public bool ChkBox_M06_9 { get; set; }
        public bool ChkBox_L40_50 { get; set; }
        public bool ChkBox_M45_9 { get; set; }
        public bool ChkBox_K50_90 { get; set; }
        public bool ChkBox_M32_10 { get; set; }
        public bool ChkBox_L40_8 { get; set; }
        public bool ChkBox_Empty { get; set; }
        public bool ChkBox_Other { get; set; }
        public string Other_TxtBox { get; set; }
        public string CLINICAL_DX_Code_TxtBox { get; set; }
        public string CLINICAL_DrugAllergies_TxtBox { get; set; }
        public bool ChkBox_Prior1 { get; set; }
        public string LengthofTreatment_TxtBox1 { get; set; }
        public bool Chkbox_ReasonforDiscontinuing1 { get; set; }
        public string ReasonforDiscontinuing1_TxtBox { get; set; }
        public bool ChkBox_Prior2 { get; set; }
        public string LengthofTreatment_TxtBox2 { get; set; }
        public bool Chkbox_ReasonforDiscontinuing2 { get; set; }
        public string ReasonforDiscontinuing2_TxtBox2 { get; set; }
        public bool ChkBox_Prior3 { get; set; }
        public string LengthofTreatment_TxtBox3 { get; set; }
        public bool Chkbox_ReasonforDiscontinuing3 { get; set; }
        public string ReasonforDiscontinuing3_TxtBox3 { get; set; }
        public bool ChkBox_latexallergy_Yes { get; set; }
        public bool ChkBox_latexallergy_No { get; set; }
        public bool ChkBox_beforestart_Yes { get; set; }
        public bool ChkBox_beforestart_No { get; set; }
        public bool ChkBox_Actemra { get; set; }
        public bool ChkBox_162mg { get; set; }
        public bool ChkBox_vial { get; set; }
        public string Vial_TxtBox { get; set; }
        public bool ChkBox_Inject162mgsubcutaneously { get; set; }
        public bool ChkBox_ONCEaweek { get; set; }
        public bool ChkBox_everyOTHERweek { get; set; }
        public string Refills_TxtBox1 { get; set; }
        public bool ChkBox_Benlysta { get; set; }
        public bool ChkBox_120mg { get; set; }
        public bool ChkBox_400mg { get; set; }
        public bool ChkBox_Infuse1 { get; set; }
        public string Infuse1_TxtBox { get; set; }
        public bool ChkBox_Infuse2 { get; set; }
        public string Infuse2_TxtBox { get; set; }
        public string Refills_TxtBox2 { get; set; }
        public bool ChkBox_Cimzia { get; set; }
        public bool ChkBox_200PrefilledSyringe { get; set; }
        public bool ChkBox_200LYOPowder { get; set; }
        public bool ChkBox_StarterKit { get; set; }
        public bool ChkBox_Maintenance { get; set; }
        public bool ChkBox_Inject200mg { get; set; }
        public string Refills_TxtBox3 { get; set; }
        public bool ChkBox_Cosentyx { get; set; }
        public bool ChkBox_300mg { get; set; }
        public bool ChkBox_PFS { get; set; }
        public bool ChkBox_150mgPen { get; set; }
        public bool ChkBox_PFS2 { get; set; }
        public bool ChkBox_Load { get; set; }
        public bool ChkBox_300mg2 { get; set; }
        public bool ChkBox_150mgsubcutaneously { get; set; }
        public bool ChkBox_Maintenance2 { get; set; }
        public bool ChkBox_300mg3 { get; set; }
        public bool ChkBox_150mgsubcutaneously2 { get; set; }
        public string Refills_TxtBox4 { get; set; }
        public bool ChkBox_Enbrel { get; set; }
        public bool ChkBox_Enbrel50mgSureclick { get; set; }
        public bool ChkBox_Enbrel50mgPrefilledSyringe { get; set; }
        public bool ChkBox_Enbrel25mgPFS { get; set; }
        public bool ChkBox_EnbrelVials { get; set; }
        public bool ChkBox_EnbrelInject50mgsubcutaneouslyONCE { get; set; }
        public bool ChkBox_Enbrelnject50mgsubcutaneouslyTWICE { get; set; }
        public string Refills_TxtBox5 { get; set; }
        public bool ChkBox_Humira { get; set; }
        public bool ChkBox_Humira40mgPen { get; set; }
        public bool ChkBox_Humira40mgPrefilledSyringe { get; set; }
        public bool ChkBox_HumiraInject40mgsubcutaneouslyevery { get; set; }
        public bool ChkBox_HumiraInject40mgsubcutaneouslyONCE { get; set; }
        public string Refills_TxtBox6 { get; set; }
        public bool ChkBox_Orencia { get; set; }
        public bool ChkBox_Orencia125mg { get; set; }
        public bool ChkBox_OrenciaPFS { get; set; }
        public bool ChkBox_OrenciaClickJect { get; set; }
        public bool ChkBox_Orencia250mg { get; set; }
        public bool ChkBox_OrenciaInject125mg { get; set; }
        public bool ChkBox_OrenciaInfuse { get; set; }
        public string OrenciaInfuse_TxtBox { get; set; }
        public string Orenciamgat_TxtBox1 { get; set; }
        public string Refills_TxtBox7 { get; set; }
        public bool ChkBox_Otezla { get; set; }
        public bool ChkBox_OtezlaStarterPack { get; set; }
        public bool ChkBox_Otezla230mgTablets { get; set; }
        public bool ChkBox_OtezlaEmpty { get; set; }
        public bool ChkBox_OtezlaTitrate { get; set; }
        public System.DateTime Otezla_dateprovided_TxtBox { get; set; }
        public bool ChkBox_Otezla_Maintenance { get; set; }
        public bool ChkBox_Otezla_Bridge { get; set; }
        public string Refills_TxtBox8 { get; set; }
        public bool ChkBox_Remicade { get; set; }
        public bool ChkBox_Remicade100mgVial { get; set; }
        public bool ChkBox_RemicadeInfuse { get; set; }
        public string RemicadeInfuse_TxtBox { get; set; }
        public string Remicademgat_TxtBox { get; set; }
        public string Remicadewt_TxtBox { get; set; }
        public string Refills_TxtBox9 { get; set; }
        public bool ChkBox_Rituxan { get; set; }
        public string Rituxan_TxtBox { get; set; }
        public string RituxanInfuse_TxtBox { get; set; }
        public bool ChkBox_RituxanInfuse { get; set; }
        public string Rituxanmgat_TxtBox { get; set; }
        public string Refills_TxtBox10 { get; set; }
        public bool ChkBox_Simponi { get; set; }
        public bool ChkBox_Simponi50mgSmartJect { get; set; }
        public bool ChkBox_SimponiPFS { get; set; }
        public bool ChkBox_SimponiAria { get; set; }
        public bool ChkBox_SimponiInject50mgsubcutaneouslyONCE { get; set; }
        public bool ChkBox_SimponiInfuse { get; set; }
        public string SimponiInfusemgatweeks0and4 { get; set; }
        public string Refills_TxtBox11 { get; set; }
        public bool ChkBox_Stelara { get; set; }
        public bool ChkBox_Stelara45mgPrefilledSyringe { get; set; }
        public bool ChkBox_StelaraInject45mgonday { get; set; }
        public bool ChkBox_StelaraInject45mgevery12 { get; set; }
        public string Refills_TxtBox12 { get; set; }
        public bool ChkBox_Xeljanz { get; set; }
        public bool ChkBox_Xeljanz5mgTablets { get; set; }
        public bool ChkBox_Xeljanz11mgXRTablets { get; set; }
        public bool ChkBox_Xeljanz1tabletbymouthtwice { get; set; }
        public bool ChkBox_Xeljanz1tabletbymouthonce { get; set; }
        public string Refills_TxtBox13 { get; set; }
        public string Refills_TxtBox14 { get; set; }
        public bool ChkBox_Others { get; set; }
        public string Others_TxtBox1 { get; set; }
        public string Others_TxtBox2 { get; set; }
        public string Others_TxtBox1_Qty { get; set; }
        public string Refills_TxtBox15 { get; set; }
        public string Prior2_TxtBox { get; set; }
        public string Prior3_TxtBox { get; set; }
        public string Actemra_Infuse_TxtBox { get; set; }
        public string Actemra_mgat_TxtBox { get; set; }
        public bool ChkBox_Actemra_Infuse { get; set; }
        public bool ChkBox_Kevzara { get; set; }
        public bool ChkBox_200mgPrefilledSyringe { get; set; }
        public bool ChkBox_150mgPrefilledSyringe { get; set; }
        public string Kevzara_Refills_TxtBox { get; set; }
    }
}