//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public long AuditId { get; set; }
        public string LogMessage { get; set; }
        public Nullable<System.DateTime> AuditStamp { get; set; }
        public string Data { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AuditOperationTypeId { get; set; }
        public string Url { get; set; }
        public string IPAddress { get; set; }
        public string Device { get; set; }
        public string RecordType { get; set; }
    
        public virtual AuditOperationType AuditOperationType { get; set; }
        public virtual User User { get; set; }
    }
}
