//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDrug
    {
        public int DrugId { get; set; }
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string NationalDrugCode { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public string Strength { get; set; }
        public string StrengthUnit { get; set; }
        public string GenericProductIdentifier { get; set; }
        public string TreatmentName { get; set; }
        public string TherapyGroup { get; set; }
        public string DrugShortName { get; set; }
        public string TherapyClassName { get; set; }
        public string Category { get; set; }
        public string ControlledSubstanceSchedule { get; set; }
        public string Branded { get; set; }
        public Nullable<System.DateTime> FirstAvailableDate { get; set; }
        public string IsCoreTherapyDrug { get; set; }
    }
}
