//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDocument
    {
        public int DocumentId { get; set; }
        public string FolderFileName { get; set; }
        public string FolderFileNameUNC { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string SubmittedToPath { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string DocumentName { get; set; }
    }
}
