//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public int PharmacyId { get; set; }
        public string ERPCode { get; set; }
        public string PharmacyName { get; set; }
        public Nullable<int> RecordSourceId { get; set; }
        public string CompanyCode { get; set; }
        public string NABP { get; set; }
        public string DEANumber { get; set; }
        public string NationalProviderIdentifier { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string StateProvince { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
    }
}
