//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianPortalPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicianPortalPatient()
        {
            this.PhysicianPortalPatient_ReferralForm_Relationship = new HashSet<PhysicianPortalPatient_ReferralForm_Relationship>();
            this.PhysicianPortalPatientChecklistRelationships = new HashSet<PhysicianPortalPatientChecklistRelationship>();
        }
    
        public int PhysicianPortalPatientId { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string PreferredLanguage { get; set; }
        public string AddressLine1 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public string EligibilityValue { get; set; }
        public string PokitDok_TradingPartnerId { get; set; }
        public string ERPCode { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string SSN { get; set; }
        public string PolicyNumber { get; set; }
        public string GroupNumber { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
    
        public virtual PokitDok_TradingPartner PokitDok_TradingPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianPortalPatient_ReferralForm_Relationship> PhysicianPortalPatient_ReferralForm_Relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianPortalPatientChecklistRelationship> PhysicianPortalPatientChecklistRelationships { get; set; }
    }
}
