//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianPortalPatientChecklistRelationship
    {
        public int PhysicianPortalPatientChecklistRelationshipId { get; set; }
        public Nullable<int> PhysicianPortalPatientId { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileContentLength { get; set; }
        public string FileExtension { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<bool> IsNotNeeded { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> ReferralFormChecklistRelationshipId { get; set; }
        public Nullable<bool> IsSubmited { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual PhysicianPortalPatient PhysicianPortalPatient { get; set; }
        public virtual ReferralFormChecklistRelationship ReferralFormChecklistRelationship { get; set; }
    }
}
