//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianPortalPatient_ReferralForm_Relationship
    {
        public int PhysicianPortalPatient_ReferralForm_RelationshipId { get; set; }
        public Nullable<int> PhysicianPortalPatientId { get; set; }
        public Nullable<int> ReferralFormId { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<System.DateTime> FilledOn { get; set; }
        public Nullable<int> FilledBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual PhysicianPortalPatient PhysicianPortalPatient { get; set; }
        public virtual ReferralForm ReferralForm { get; set; }
    }
}
