//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferralForm()
        {
            this.PhysicianPortalPatient_ReferralForm_Relationship = new HashSet<PhysicianPortalPatient_ReferralForm_Relationship>();
            this.ReferralFormChecklistRelationships = new HashSet<ReferralFormChecklistRelationship>();
        }
    
        public int ReferralFormId { get; set; }
        public string ReferralFormName { get; set; }
        public string ReferralFormValue { get; set; }
        public Nullable<int> ReferralFormCategoryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianPortalPatient_ReferralForm_Relationship> PhysicianPortalPatient_ReferralForm_Relationship { get; set; }
        public virtual ReferralFormCategory ReferralFormCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralFormChecklistRelationship> ReferralFormChecklistRelationships { get; set; }
    }
}
