//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralFormChecklistRelationship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferralFormChecklistRelationship()
        {
            this.PhysicianPortalPatientChecklistRelationships = new HashSet<PhysicianPortalPatientChecklistRelationship>();
        }
    
        public int ReferralFormChecklistRelationshipId { get; set; }
        public Nullable<int> ReferralFormId { get; set; }
        public Nullable<int> ChecklistId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicianPortalPatientChecklistRelationship> PhysicianPortalPatientChecklistRelationships { get; set; }
        public virtual ReferralForm ReferralForm { get; set; }
    }
}
