//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormGeneralintake
    {
        public int RefFormGeneralintakeId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public string Diagnosis_TxtBox { get; set; }
        public string DrugAllergies_TxtBox { get; set; }
        public string PFM_TextBox1 { get; set; }
        public string LOT_TextBox1 { get; set; }
        public string ROD_TextBox1 { get; set; }
        public string PFM_TextBox2 { get; set; }
        public string LOT_TextBox2 { get; set; }
        public string ROD_TextBox2 { get; set; }
        public string PFM_TextBox3 { get; set; }
        public string LOT_TextBox3 { get; set; }
        public string ROD_TextBox3 { get; set; }
        public string PFM_TextBox4 { get; set; }
        public string LOT_TextBox4 { get; set; }
        public string ROD_TextBox4 { get; set; }
        public string Med_TxtBox1 { get; set; }
        public string Strength_TxtBox1 { get; set; }
        public string Dose_TxtBox1 { get; set; }
        public string Qty_TxtBox1 { get; set; }
        public string Refills_TxtBox1 { get; set; }
        public string Med_TxtBox2 { get; set; }
        public string Strength_TxtBox2 { get; set; }
        public string Dose_TxtBox2 { get; set; }
        public string Qty_TxtBox2 { get; set; }
        public string Refills_TxtBox2 { get; set; }
        public string Med_TxtBox3 { get; set; }
        public string Strength_TxtBox3 { get; set; }
        public string Dose_TxtBox3 { get; set; }
        public string Qty_TxtBox3 { get; set; }
        public string Refills_TxtBox3 { get; set; }
        public string Med_TxtBox4 { get; set; }
        public string Strength_TxtBox4 { get; set; }
        public string Dose_TxtBox4 { get; set; }
        public string Qty_TxtBox4 { get; set; }
        public string Refills_TxtBox4 { get; set; }
        public string Med_TxtBox5 { get; set; }
        public string Strength_TxtBox5 { get; set; }
        public string Dose_TxtBox5 { get; set; }
        public string Qty_TxtBox5 { get; set; }
        public string Refills_TxtBox5 { get; set; }
        public string Med_TxtBox6 { get; set; }
        public string Strength_TxtBox6 { get; set; }
        public string Dose_TxtBox6 { get; set; }
        public string Qty_TxtBox6 { get; set; }
        public string Refills_TxtBox6 { get; set; }
        public string Med_TxtBox7 { get; set; }
        public string Strength_TxtBox7 { get; set; }
        public string Dose_TxtBox7 { get; set; }
        public string Qty_TxtBox7 { get; set; }
        public string Refills_TxtBox7 { get; set; }
        public string Med_TxtBox8 { get; set; }
        public string Strength_TxtBox8 { get; set; }
        public string Dose_TxtBox8 { get; set; }
        public string Qty_TxtBox8 { get; set; }
        public string Refills_TxtBox8 { get; set; }
        public string Med_TxtBox9 { get; set; }
        public string Strength_TxtBox9 { get; set; }
        public string Dose_TxtBox9 { get; set; }
        public string Qty_TxtBox9 { get; set; }
        public string Refills_TxtBox9 { get; set; }
        public string Med_TxtBox10 { get; set; }
        public string Strength_TxtBox10 { get; set; }
        public string Dose_TxtBox10 { get; set; }
        public string Qty_TxtBox10 { get; set; }
        public string Refills_TxtBox10 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
    }
}
