//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormOncology_2
    {
        public int RefFormOncologyId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public string PrimaryDiagnosis_TxtBox { get; set; }
        public string ICD_10_TxtBox1 { get; set; }
        public string SecondaryDiagnosis_TxtBox { get; set; }
        public string ICD_10_TxtBox2 { get; set; }
        public string DrugAllergies_TxtBox { get; set; }
        public Nullable<double> Weight_TxtBox { get; set; }
        public Nullable<double> Height_TxtBox { get; set; }
        public string BodySurfaceArea_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ABRAXANE { get; set; }
        public string ABRAXANE_Strength_TxtBox { get; set; }
        public string ABRAXANE_SIG_TxtBox { get; set; }
        public string ABRAXANE_CYCLES_TxtBox { get; set; }
        public string ABRAXANE_QUANTITY_TxtBox { get; set; }
        public string ABRAXANE_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ADCETRIS { get; set; }
        public string ADCETRIS_Strength_TxtBox { get; set; }
        public string ADCETRIS_SIG_TxtBox { get; set; }
        public string ADCETRIS_CYCLES_TxtBox { get; set; }
        public string ADCETRIS_QUANTITY_TxtBox { get; set; }
        public string ADCETRIS_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ALIMTA { get; set; }
        public string ALIMTA_Strength_TxtBox { get; set; }
        public string ALIMTA_SIG_TxtBox { get; set; }
        public string ALIMTA_CYCLES_TxtBox { get; set; }
        public string ALIMTA_QUANTITY_TxtBox { get; set; }
        public string ALIMTA_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_AVASTIN { get; set; }
        public string AVASTIN_Strength_TxtBox { get; set; }
        public string AVASTIN_SIG_TxtBox { get; set; }
        public string AVASTIN_CYCLES_TxtBox { get; set; }
        public string AVASTIN_QUANTITY_TxtBox { get; set; }
        public string AVASTIN_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_CARBOPLATIN { get; set; }
        public string CARBOPLATIN_Strength_TxtBox { get; set; }
        public string CARBOPLATIN_SIG_TxtBox { get; set; }
        public string CARBOPLATIN_CYCLES_TxtBox { get; set; }
        public string CARBOPLATIN_QUANTITY_TxtBox { get; set; }
        public string CARBOPLATIN_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ELOXATIN { get; set; }
        public string ELOXATIN_Strength_TxtBox { get; set; }
        public string ELOXATIN_SIG_TxtBox { get; set; }
        public string ELOXATIN_CYCLES_TxtBox { get; set; }
        public string ELOXATIN_QUANTITY_TxtBox { get; set; }
        public string ELOXATIN_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_HERCEPTIN { get; set; }
        public string HERCEPTIN_Strength_TxtBox { get; set; }
        public string HERCEPTIN_SIG_TxtBox { get; set; }
        public string HERCEPTIN_CYCLES_TxtBox { get; set; }
        public string HERCEPTIN_QUANTITY_TxtBox { get; set; }
        public string HERCEPTIN_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_RITUXAN { get; set; }
        public string RITUXAN_Strength_TxtBox { get; set; }
        public string RITUXAN_SIG_TxtBox { get; set; }
        public string RITUXAN_CYCLES_TxtBox { get; set; }
        public string RITUXAN_QUANTITY_TxtBox { get; set; }
        public string RITUXAN_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_CISPLATIN { get; set; }
        public string CISPLATIN_Strength_TxtBox { get; set; }
        public string CISPLATIN_SIG_TxtBox { get; set; }
        public string CISPLATIN_CYCLES_TxtBox { get; set; }
        public string CISPLATIN_QUANTITY_TxtBox { get; set; }
        public string CISPLATIN_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_DOCETAXEL { get; set; }
        public string DOCETAXEL_Strength_TxtBox { get; set; }
        public string DOCETAXEL_SIG_TxtBox { get; set; }
        public string DOCETAXEL_CYCLES_TxtBox { get; set; }
        public string DOCETAXEL_QUANTITY_TxtBox { get; set; }
        public string DOCETAXEL_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ERBITUX { get; set; }
        public string ERBITUX_Strength_TxtBox { get; set; }
        public string ERBITUX_SIG_TxtBox { get; set; }
        public string ERBITUX_CYCLES_TxtBox { get; set; }
        public string ERBITUX_QUANTITY_TxtBox { get; set; }
        public string ERBITUX_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_GEMCITABINE { get; set; }
        public string GEMCITABINE_Strength_TxtBox { get; set; }
        public string GEMCITABINE_SIG_TxtBox { get; set; }
        public string GEMCITABINE_CYCLES_TxtBox { get; set; }
        public string GEMCITABINE_QUANTITY_TxtBox { get; set; }
        public string GEMCITABINE_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_KADCYLA { get; set; }
        public string KADCYLA_Strength_TxtBox { get; set; }
        public string KADCYLA_SIG_TxtBox { get; set; }
        public string KADCYLA_CYCLES_TxtBox { get; set; }
        public string KADCYLA_QUANTITY_TxtBox { get; set; }
        public string KADCYLA_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_PACLITAXEL { get; set; }
        public string PACLITAXEL_Strength_TxtBox { get; set; }
        public string PACLITAXEL_SIG_TxtBox { get; set; }
        public string PACLITAXEL_CYCLES_TxtBox { get; set; }
        public string PACLITAXEL_QUANTITY_TxtBox { get; set; }
        public string PACLITAXEL_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_TORISEL { get; set; }
        public string TORISEL_Strength_TxtBox { get; set; }
        public string TORISEL_SIG_TxtBox { get; set; }
        public string TORISEL_CYCLES_TxtBox { get; set; }
        public string TORISEL_QUANTITY_TxtBox { get; set; }
        public string TORISEL_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_VELCADE { get; set; }
        public string VELCADE_Strength_TxtBox { get; set; }
        public string VELCADE_SIG_TxtBox { get; set; }
        public string VELCADE_CYCLES_TxtBox { get; set; }
        public string VELCADE_QUANTITY_TxtBox { get; set; }
        public string VELCADE_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ZOMETA { get; set; }
        public string ZOMETA_Strength_TxtBox { get; set; }
        public string ZOMETA_SIG_TxtBox { get; set; }
        public string ZOMETA_CYCLES_TxtBox { get; set; }
        public string ZOMETA_QUANTITY_TxtBox { get; set; }
        public string ZOMETA_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER1 { get; set; }
        public string OTHER1_Strength_TxtBox { get; set; }
        public string OTHER1_SIG_TxtBox { get; set; }
        public string OTHER1_CYCLES_TxtBox { get; set; }
        public string OTHER1_QUANTITY_TxtBox { get; set; }
        public string OTHER1_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER2 { get; set; }
        public string OTHER2_Strength_TxtBox { get; set; }
        public string OTHER2_SIG_TxtBox { get; set; }
        public string OTHER2_CYCLES_TxtBox { get; set; }
        public string OTHER2_QUANTITY_TxtBox { get; set; }
        public string OTHER2_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER3 { get; set; }
        public string OTHER3_Strength_TxtBox { get; set; }
        public string OTHER3_SIG_TxtBox { get; set; }
        public string OTHER3_CYCLES_TxtBox { get; set; }
        public string OTHER3_QUANTITY_TxtBox { get; set; }
        public string OTHER3_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_DEXAMETHASONE { get; set; }
        public string DEXAMETHASONE_TxtBox { get; set; }
        public Nullable<bool> ChkBox_DIPHENHYDRAMINE { get; set; }
        public string DIPHENHYDRAMINE_TxtBox { get; set; }
        public Nullable<bool> ChkBox_RANITIDINE { get; set; }
        public string RANITIDINE_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ONDANSETRON { get; set; }
        public string ONDANSETRON_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER4 { get; set; }
        public string DOSE_TxtBox { get; set; }
        public string SIG_TxtBox { get; set; }
        public string REFILLS_TxtBox { get; set; }
        public string OTHER4_TxtBox { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
