//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormOncology_1
    {
        public int RefFormOncologyId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public string Diagnosis_TxtBox { get; set; }
        public string ICD_10_TxtBox { get; set; }
        public string DrugAllergies_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Thalomid { get; set; }
        public Nullable<bool> ChkBox_50mg { get; set; }
        public Nullable<bool> ChkBox_100mg { get; set; }
        public Nullable<bool> ChkBox_150mg { get; set; }
        public Nullable<bool> ChkBox_200mg { get; set; }
        public Nullable<bool> ChkBox_Take1capPOdaily1 { get; set; }
        public Nullable<bool> ChkBox_Empty1 { get; set; }
        public string Empty1_TxtBox { get; set; }
        public string Qty_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_AdultFemale { get; set; }
        public Nullable<bool> ChkBox_AdultFemaleNOT { get; set; }
        public Nullable<bool> ChkBox_AdultMale { get; set; }
        public Nullable<bool> ChkBox_Pomalyst { get; set; }
        public Nullable<bool> ChkBox_1mg { get; set; }
        public Nullable<bool> ChkBox_2mg { get; set; }
        public Nullable<bool> ChkBox_3mg { get; set; }
        public Nullable<bool> ChkBox_4mg { get; set; }
        public Nullable<bool> ChkBox_Take1capPOdailydays1_21of28daycycle1 { get; set; }
        public Nullable<bool> ChkBox_Empty2 { get; set; }
        public string Empty2_TxtBox { get; set; }
        public string Qty_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_FemaleChild { get; set; }
        public Nullable<bool> ChkBox_FemaleChildNOT { get; set; }
        public Nullable<bool> ChkBox_MaleChild { get; set; }
        public Nullable<bool> ChkBox_Revlimid { get; set; }
        public Nullable<bool> ChkBox_2_5mg { get; set; }
        public Nullable<bool> ChkBox_5mg { get; set; }
        public Nullable<bool> ChkBox_10mg { get; set; }
        public Nullable<bool> ChkBox_15mg { get; set; }
        public Nullable<bool> ChkBox_20mg { get; set; }
        public Nullable<bool> ChkBox_25mg { get; set; }
        public Nullable<bool> ChkBox_Take1capPOdaily2 { get; set; }
        public Nullable<bool> ChkBox_Take1capPOdailydays1_21of28daycycle2 { get; set; }
        public Nullable<bool> ChkBox_Empty3 { get; set; }
        public string Empty3_TxtBox { get; set; }
        public string Qty_TxtBox3 { get; set; }
        public string Authorization_TxtBox { get; set; }
        public Nullable<System.DateTime> Date1_TxtBox { get; set; }
        public string Confirmation_TxtBox { get; set; }
        public Nullable<System.DateTime> Date2_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Ninlaro { get; set; }
        public Nullable<bool> ChkBox_4mg2 { get; set; }
        public Nullable<bool> ChkBox_3mg2 { get; set; }
        public Nullable<bool> ChkBox_2_3mg { get; set; }
        public string Refills_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_Dexamethasone { get; set; }
        public string Dexamethasone_Qty_TxtBox { get; set; }
        public string Dexamethasone_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Empty4 { get; set; }
        public string Empty4_Qty_TxtBox { get; set; }
        public string Empty4_Refills_TxtBox { get; set; }
        public string Empty4_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Others { get; set; }
        public string Others_TxtBox { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
