//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormDermatology
    {
        public int RefFormDermatologyId { get; set; }
        public Nullable<bool> ChkBox_L40_8_Moderate_to_Severe_Plaque_Psoriasis { get; set; }
        public Nullable<bool> ChkBox_L40_50_Psoriatic_Arthritis { get; set; }
        public Nullable<bool> ChkBox_L73_2_Hidradenitis_Suppurativa_Hurley_Stage { get; set; }
        public string TxtBox_L73_2_Hidradenitis_Suppurativa_Hurley_Stage { get; set; }
        public Nullable<bool> ChkBox_Other_Dx_code { get; set; }
        public string TxtBox_Other_Dx_code { get; set; }
        public string TxtBox_Condition { get; set; }
        public string TxtBox_Drug_Allergies { get; set; }
        public string TxtBox_Location_BSA { get; set; }
        public Nullable<bool> ChkBox_Hands { get; set; }
        public Nullable<bool> ChkBox_Feet { get; set; }
        public Nullable<bool> ChkBox_Scalp { get; set; }
        public Nullable<bool> ChkBox_Groin { get; set; }
        public Nullable<bool> ChkBox_Nails { get; set; }
        public Nullable<bool> ChkBox_Other { get; set; }
        public string TxtBox_Other { get; set; }
        public Nullable<bool> ChkBox_Biologics { get; set; }
        public Nullable<bool> ChkBox_Cimzia { get; set; }
        public Nullable<bool> ChkBox_Cosentyx { get; set; }
        public Nullable<bool> ChkBox_Enbrel { get; set; }
        public Nullable<bool> ChkBox_Humira { get; set; }
        public Nullable<bool> ChkBox_Orencia { get; set; }
        public Nullable<bool> ChkBox_Remicade { get; set; }
        public Nullable<bool> ChkBox_Rituxan { get; set; }
        public Nullable<bool> ChkBox_Simponi { get; set; }
        public Nullable<bool> ChkBox_Stelara { get; set; }
        public Nullable<bool> ChkBox_MTX { get; set; }
        public Nullable<bool> ChkBox_Soriatane { get; set; }
        public Nullable<bool> ChkBox_CYA { get; set; }
        public string TxtBox_CYA_Length_of_Treatment { get; set; }
        public string TxtBox_CYA_Reason_for_Discontinuing { get; set; }
        public Nullable<bool> ChkBox_PUVA_UVB { get; set; }
        public string TxtBox_PUVA_UVB_Length_of_Treatment { get; set; }
        public string TxtBox_PUVA_UVB_Reason_for_Discontinuing { get; set; }
        public Nullable<bool> ChkBox_Topicals { get; set; }
        public string TxtBox_Topicals_Length_of_Treatment { get; set; }
        public string TxtBox_Topicals_Inadequate_Response_List_Specific_Names { get; set; }
        public Nullable<bool> ChkBox_Contraindicated { get; set; }
        public string TxtBox_Contraindicated_Medication { get; set; }
        public string TxtBox_Contraindicated_Reason { get; set; }
        public Nullable<bool> ChkBox_Does_patient_have_a_latex_allergy { get; set; }
        public Nullable<bool> ChkBox_TB_PPD_Test_given_or_intended_to_be_given_before_start { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1 { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_300mg_2x150_Pen { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_PFS { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_150mg_Pen { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_PFS_1 { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_Load_Inject { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_300mg { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_150mg { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_Maintenance_Inject { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_300mg_1 { get; set; }
        public Nullable<bool> ChkBox_Cosentyx_1_150mg_1 { get; set; }
        public string TxtBox_Cosentyx_1_Refills { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1 { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_50mg_Sureclick { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_50mg_Prefilled_Syringe { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_25mg_Prefilled_Syringe { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_25mg_Vials { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_Inject_50mg_subcutaneously_TWICE_a_week_72_96_hours_apart { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_Inject_50mg_subcutaneously_ONCE_a_week { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_Inject_25mg_subcutaneously_TWICE_a_week_72_96_hours_apart { get; set; }
        public Nullable<bool> ChkBox_Enbrel_1_Inject_2_25mg_50mg_on_same_day_TWICE_a_week_72_96_hours_apart { get; set; }
        public string Enbrel_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Erivedge { get; set; }
        public Nullable<bool> ChkBox_Humaira { get; set; }
        public Nullable<bool> ChkBox_HumairaPsoriasisStarterKit { get; set; }
        public Nullable<bool> ChkBox_Humaira40mgPen { get; set; }
        public Nullable<bool> ChkBox_Humaira40mgPrefilledSyringe { get; set; }
        public Nullable<bool> ChkBox_HumairaInject2_40mg { get; set; }
        public Nullable<bool> ChkBox_HumairaInjectInject40mgsubcutaneouslyEVERY { get; set; }
        public Nullable<bool> ChkBox_HumairaInjectInject40mgsubcutaneouslyONCE { get; set; }
        public string Humaira_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_HumairaHS { get; set; }
        public Nullable<bool> ChkBox_HumairaHSPsoriasisStarterKit { get; set; }
        public Nullable<bool> ChkBox_HumairaHS40mgPen { get; set; }
        public Nullable<bool> ChkBox_HumairaHS40mgPrefilledSyringe { get; set; }
        public Nullable<bool> ChkBox_HumairaHSFour40mg { get; set; }
        public Nullable<bool> ChkBox_HumairaHSTwo40mg { get; set; }
        public Nullable<bool> ChkBox_HumairaHSWeek4plus { get; set; }
        public string HumairaHS_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Odomzo { get; set; }
        public string Odomzo_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Otezla { get; set; }
        public Nullable<bool> ChkBox_OtezlaStarterPack { get; set; }
        public Nullable<bool> ChkBox_Otezla30mgTablets { get; set; }
        public Nullable<bool> ChkBox_OtezlaTitrateTake1tablet { get; set; }
        public Nullable<System.DateTime> OtezlaDate_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OtezlaMaintenanceTake1tablet { get; set; }
        public Nullable<bool> ChkBox_OtezlaBridgeRxTake { get; set; }
        public string Otezla_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Remicade2 { get; set; }
        public string Remicade2_Wt_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Remicade100mgVial { get; set; }
        public Nullable<bool> ChkBox_Infuse1 { get; set; }
        public string Infuse1_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Infuse2 { get; set; }
        public string Infuse2_TxtBox2 { get; set; }
        public string Remicade2_Loadingdose_TxtBox { get; set; }
        public string Remicade2_REFILLS_TxtBox { get; set; }
        public string Remicade2_Weeks_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Simponi2 { get; set; }
        public Nullable<bool> ChkBox_Simponi250mgSmartJect { get; set; }
        public Nullable<bool> ChkBox_Simponi2PFS { get; set; }
        public string Simponi2_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Stelara2 { get; set; }
        public string Stelara2_Wt_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Stelara245mg { get; set; }
        public Nullable<bool> ChkBox_Stelara290mg { get; set; }
        public Nullable<bool> ChkBox_StelaraInject245mgonday { get; set; }
        public Nullable<bool> ChkBox_StelaraInject290mgonday { get; set; }
        public string Stelara2_REFILLS_TxtBox1 { get; set; }
        public string Stelara2_REFILLS_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_TaltzTM { get; set; }
        public Nullable<bool> ChkBox_TaltzTM80mg_mL { get; set; }
        public Nullable<bool> ChkBox_TaltzTM80mg_mLPrefilled { get; set; }
        public Nullable<bool> ChkBox_TaltzTM_LoadInject160mg { get; set; }
        public Nullable<bool> ChkBox_TaltzTM_MaintenanceDose { get; set; }
        public string TaltzTM_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Others { get; set; }
        public string Others_TxtBox1 { get; set; }
        public string Others_TxtBox2 { get; set; }
        public string Others_Qty_TxtBox { get; set; }
        public string Others_Refills_TxtBox { get; set; }
        public string Erivedge_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_nola_L20_9AtopicDermatitis { get; set; }
        public Nullable<bool> ChkBox_nola_Dupixent { get; set; }
        public Nullable<bool> ChkBox_nola_Dupixent_300mg1 { get; set; }
        public Nullable<bool> ChkBox_nola_Dupixent_300mg2 { get; set; }
        public Nullable<bool> ChkBox_nola_Dupixent_Load { get; set; }
        public Nullable<bool> ChkBox_nola_Dupixent_Mantainance { get; set; }
        public string nola_Dupixent_Refills_TxtBox { get; set; }
        public string nola_Enbrel_wt_TxtBox { get; set; }
        public Nullable<bool> ChkBox_nola_inject_0_8mg { get; set; }
        public string nola_inject_0_8mg_TxtBox { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Erivedge_TxtBox_Refills { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
    }
}
