//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormOsteoporosi
    {
        public int RefFormOsteoporosisId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public Nullable<bool> ChkBox_CLINICAL_M81_0 { get; set; }
        public Nullable<bool> ChkBox_CLINICAL_Other { get; set; }
        public string CLINICAL_DXCode { get; set; }
        public string CLINICAL_DrugAllergies { get; set; }
        public Nullable<bool> ChkBox_alendronate { get; set; }
        public string LengthofTreatment_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_ReasonforDiscontinuing1 { get; set; }
        public string ReasonforDiscontinuing1_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_bandronate { get; set; }
        public string LengthofTreatment_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_ReasonforDiscontinuing2 { get; set; }
        public string ReasonforDiscontinuing2_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_risedronate { get; set; }
        public string LengthofTreatment_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_ReasonforDiscontinuing3 { get; set; }
        public string ReasonforDiscontinuing3_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_prednisone { get; set; }
        public string LengthofTreatment_TxtBox4 { get; set; }
        public Nullable<bool> ChkBox_ReasonforDiscontinuing4 { get; set; }
        public string ReasonforDiscontinuing4_TxtBox4 { get; set; }
        public Nullable<bool> ChkBox_5 { get; set; }
        public string LengthofTreatment_TxtBox5 { get; set; }
        public Nullable<bool> ChkBox_ReasonforDiscontinuing5 { get; set; }
        public string ReasonforDiscontinuing5_TxtBox5 { get; set; }
        public string CLINICAL_BoneDensity_T_Score { get; set; }
        public string CLINICAL_BoneDensity_Type { get; set; }
        public Nullable<System.DateTime> CLINICAL_BoneDensity_Date { get; set; }
        public string CLINICAL_FractureHistorySite1 { get; set; }
        public Nullable<System.DateTime> CLINICAL_FractureHistorySite1Date { get; set; }
        public string CLINICAL_FractureHistorySite2 { get; set; }
        public Nullable<System.DateTime> CLINICAL_FractureHistorySite2Date { get; set; }
        public Nullable<bool> ChkBox_CLINICAL_patientbeenonForteo_Yes { get; set; }
        public Nullable<bool> ChkBox_CLINICAL_patientbeenonForteo_No { get; set; }
        public string CLINICAL_howlong_TxtBox { get; set; }
        public Nullable<bool> ChckBox_PatientAllergy_Yes { get; set; }
        public Nullable<bool> ChckBox_PatientAllergy_No { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Boniva { get; set; }
        public string PRESCRIPTION_Refills_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Forteo { get; set; }
        public string PRESCRIPTION_Refills_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Prolia { get; set; }
        public string PRESCRIPTION_Refills_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Reclast { get; set; }
        public string PRESCRIPTION_Refills_TxtBox4 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Other { get; set; }
        public string PRESCRIPTION_Other_TxtBox1 { get; set; }
        public string PRESCRIPTION_Other_TxtBox2 { get; set; }
        public string PRESCRIPTION_Other_TxtBox3 { get; set; }
        public string PRESCRIPTION_Other_Qty_TxtBox1 { get; set; }
        public string PRESCRIPTION_Refills_TxtBox5 { get; set; }
        public string CLINICAL_Other_TxtBox01 { get; set; }
        public string ChkBox_5_TxtBox { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
