//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormOncologyInfusion
    {
        public int RefFormOncologyInfusionId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public string CLINICAL_PrimaryDiagnosis_TxtBox { get; set; }
        public string CLINICAL_Primary_ICD_10 { get; set; }
        public string CLINICAL_SecondaryDiagnosis_TxtBox { get; set; }
        public string CLINICAL_Secondary_ICD_10 { get; set; }
        public string CLINICAL_DrugAllergies_TxtBox { get; set; }
        public Nullable<double> CLINICAL_PatientWeight { get; set; }
        public Nullable<double> CLINICAL_PatientHeight { get; set; }
        public Nullable<double> CLINICAL_BodySurfaceArea { get; set; }
        public Nullable<bool> ChkBox_ABRAXANE { get; set; }
        public string ABRAXANE_Strength_TxtBox { get; set; }
        public string ABRAXANE_SIG_TxtBox { get; set; }
        public string ABRAXANE_CYCLES_TxtBox { get; set; }
        public string ABRAXANE_Quantity_TxtBox { get; set; }
        public string ABRAXANE_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ADCETRIS { get; set; }
        public string ADCETRIS_Strength_TxtBox { get; set; }
        public string ADCETRIS_SIG_TxtBox { get; set; }
        public string ADCETRIS_CYCLES_TxtBox { get; set; }
        public string ADCETRIS_Quantity_TxtBox { get; set; }
        public string ADCETRIS_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ALIMTA { get; set; }
        public string ALIMTA_Strength_TxtBox { get; set; }
        public string ALIMTA_SIG_TxtBox { get; set; }
        public string ALIMTA_CYCLES_TxtBox { get; set; }
        public string ALIMTA_Quantity_TxtBox { get; set; }
        public string ALIMTA_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_AVASTIN { get; set; }
        public string AVASTIN_Strength_TxtBox { get; set; }
        public string AVASTIN_SIG_TxtBox { get; set; }
        public string AVASTIN_CYCLES_TxtBox { get; set; }
        public string AVASTIN_Quantity_TxtBox { get; set; }
        public string AVASTIN_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_CARBOPLATIN { get; set; }
        public string CARBOPLATIN_Strength_TxtBox { get; set; }
        public string CARBOPLATIN_SIG_TxtBox { get; set; }
        public string CARBOPLATIN_CYCLES_TxtBox { get; set; }
        public string CARBOPLATIN_Quantity_TxtBox { get; set; }
        public string CARBOPLATIN_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ELOXATIN { get; set; }
        public string ELOXATIN_Strength_TxtBox { get; set; }
        public string ELOXATIN_SIG_TxtBox { get; set; }
        public string ELOXATIN_CYCLES_TxtBox { get; set; }
        public string ELOXATIN_Quantity_TxtBox { get; set; }
        public string ELOXATIN_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_HERCEPTIN { get; set; }
        public string HERCEPTIN_Strength_TxtBox { get; set; }
        public string HERCEPTIN_SIG_TxtBox { get; set; }
        public string HERCEPTIN_CYCLES_TxtBox { get; set; }
        public string HERCEPTIN_Quantity_TxtBox { get; set; }
        public string HERCEPTIN_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_RITUXAN { get; set; }
        public string RITUXAN_Strength_TxtBox { get; set; }
        public string RITUXAN_SIG_TxtBox { get; set; }
        public string RITUXAN_CYCLES_TxtBox { get; set; }
        public string RITUXAN_Quantity_TxtBox { get; set; }
        public string RITUXAN_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_CISPLATIN { get; set; }
        public string CISPLATIN_Strength_TxtBox { get; set; }
        public string CISPLATIN_SIG_TxtBox { get; set; }
        public string CISPLATIN_CYCLES_TxtBox { get; set; }
        public string CISPLATIN_Quantity_TxtBox { get; set; }
        public string CISPLATIN_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_DOCETAXEL { get; set; }
        public string DOCETAXEL_Strength_TxtBox { get; set; }
        public string DOCETAXEL_SIG_TxtBox { get; set; }
        public string DOCETAXEL_CYCLES_TxtBox { get; set; }
        public string DOCETAXEL_Quantity_TxtBox { get; set; }
        public string DOCETAXEL_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ERBITUX { get; set; }
        public string ERBITUX_Strength_TxtBox { get; set; }
        public string ERBITUX_SIG_TxtBox { get; set; }
        public string ERBITUX_CYCLES_TxtBox { get; set; }
        public string ERBITUX_Quantity_TxtBox { get; set; }
        public string ERBITUX_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_GEMCITABINE { get; set; }
        public string GEMCITABINE_Strength_TxtBox { get; set; }
        public string GEMCITABINE_SIG_TxtBox { get; set; }
        public string GEMCITABINE_CYCLES_TxtBox { get; set; }
        public string GEMCITABINE_Quantity_TxtBox { get; set; }
        public string GEMCITABINE_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_KADCYLA { get; set; }
        public string KADCYLA_Strength_TxtBox { get; set; }
        public string KADCYLA_SIG_TxtBox { get; set; }
        public string KADCYLA_CYCLES_TxtBox { get; set; }
        public string KADCYLA_Quantity_TxtBox { get; set; }
        public string KADCYLA_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_PACLITAXEL { get; set; }
        public string PACLITAXEL_Strength_TxtBox { get; set; }
        public string PACLITAXEL_SIG_TxtBox { get; set; }
        public string PACLITAXEL_CYCLES_TxtBox { get; set; }
        public string PACLITAXEL_Quantity_TxtBox { get; set; }
        public string PACLITAXEL_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_TORISEL { get; set; }
        public string TORISEL_Strength_TxtBox { get; set; }
        public string TORISEL_SIG_TxtBox { get; set; }
        public string TORISEL_CYCLES_TxtBox { get; set; }
        public string TORISEL_Quantity_TxtBox { get; set; }
        public string TORISEL_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_VELCADE { get; set; }
        public string VELCADE_Strength_TxtBox { get; set; }
        public string VELCADE_SIG_TxtBox { get; set; }
        public string VELCADE_CYCLES_TxtBox { get; set; }
        public string VELCADE_Quantity_TxtBox { get; set; }
        public string VELCADE_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ZOMETA { get; set; }
        public string ZOMETA_Strength_TxtBox { get; set; }
        public string ZOMETA_SIG_TxtBox { get; set; }
        public string ZOMETA_CYCLES_TxtBox { get; set; }
        public string ZOMETA_Quantity_TxtBox { get; set; }
        public string ZOMETA_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER1 { get; set; }
        public string OTHER1_Strength_TxtBox { get; set; }
        public string OTHER1_SIG_TxtBox { get; set; }
        public string OTHER1_CYCLES_TxtBox { get; set; }
        public string OTHER1_Quantity_TxtBox { get; set; }
        public string OTHER1_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER2 { get; set; }
        public string OTHER2_Strength_TxtBox { get; set; }
        public string OTHER2_SIG_TxtBox { get; set; }
        public string OTHER2_CYCLES_TxtBox { get; set; }
        public string OTHER2_Quantity_TxtBox { get; set; }
        public string OTHER2_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER3 { get; set; }
        public string OTHER3_Strength_TxtBox { get; set; }
        public string OTHER3_SIG_TxtBox { get; set; }
        public string OTHER3_CYCLES_TxtBox { get; set; }
        public string OTHER3_Quantity_TxtBox { get; set; }
        public string OTHER3_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_DEXAMETHASONE { get; set; }
        public string DEXAMETHASONE_TxtBox { get; set; }
        public Nullable<bool> ChkBox_DIPHENHYDRAMINE { get; set; }
        public string DIPHENHYDRAMINE_TxtBox { get; set; }
        public Nullable<bool> ChkBox_RANITIDINE { get; set; }
        public string RANITIDINE_TxtBox { get; set; }
        public Nullable<bool> ChkBox_ONDANSETRON { get; set; }
        public string ONDANSETRON_TxtBox { get; set; }
        public Nullable<bool> ChkBox_OTHER { get; set; }
        public string OTHER_TxtBox { get; set; }
        public string DOSE_TxtBox { get; set; }
        public string SIG_TxtBox { get; set; }
        public string REFILLS_TxtBox { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
