//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormGrowthHormone
    {
        public int RefFormGrowthHormoneId { get; set; }
        public string CLINICAL_Diagnosis_TxtBox { get; set; }
        public string CLINICAL_ICD_10 { get; set; }
        public string CLINICAL_Drug_Allergies { get; set; }
        public Nullable<bool> ChkBox_Epiphysis_open_Yes { get; set; }
        public Nullable<bool> ChkBox_Epiphysis_open_No { get; set; }
        public Nullable<int> CLINICAL_Drug_BoneAge { get; set; }
        public string CLINICAL_Drug_Growth_Velocity { get; set; }
        public string CLINICAL_Strim1_TxtBox1 { get; set; }
        public string CLINICAL_Strim1_TxtBox2 { get; set; }
        public string CLINICAL_Strim1_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_Pass1 { get; set; }
        public Nullable<bool> ChkBox_Fail1 { get; set; }
        public Nullable<double> CLINICAL_Patent_Weight_TxtBox { get; set; }
        public Nullable<double> CLINICAL_Patent_Height_TxtBox { get; set; }
        public string CLINICAL_Strim2_TxtBox1 { get; set; }
        public string CLINICAL_Strim2_TxtBox2 { get; set; }
        public string CLINICAL_Strim2_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_Pass2 { get; set; }
        public Nullable<bool> ChkBox_Fail2 { get; set; }
        public Nullable<bool> ChkBox_Genotropin { get; set; }
        public Nullable<bool> ChkBox_cartridge1 { get; set; }
        public Nullable<bool> ChkBox_5mg1 { get; set; }
        public Nullable<bool> ChkBox_12mg1 { get; set; }
        public string SIG_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_mini_quick { get; set; }
        public Nullable<bool> ChkBox_0_2mg1 { get; set; }
        public Nullable<bool> ChkBox_0_4mg1 { get; set; }
        public Nullable<bool> ChkBox_0_6mg1 { get; set; }
        public Nullable<bool> ChkBox_0_8mg1 { get; set; }
        public Nullable<bool> ChkBox_1_0mg1 { get; set; }
        public Nullable<bool> ChkBox_1_2mg1 { get; set; }
        public Nullable<bool> ChkBox_1_4mg1 { get; set; }
        public Nullable<bool> ChkBox_1_6mg1 { get; set; }
        public Nullable<bool> ChkBox_1_8mg1 { get; set; }
        public Nullable<bool> ChkBox_2mg1 { get; set; }
        public string RF_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_Humatrope { get; set; }
        public Nullable<bool> ChkBox_cartridge2 { get; set; }
        public Nullable<bool> ChkBox_6mg1 { get; set; }
        public Nullable<bool> ChkBox_12mg2 { get; set; }
        public Nullable<bool> ChkBox_24mg1 { get; set; }
        public string SIG_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_vial1 { get; set; }
        public string RF_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_Norditropin { get; set; }
        public Nullable<bool> ChkBox_FlexPro { get; set; }
        public Nullable<bool> ChkBox_5mg2 { get; set; }
        public Nullable<bool> ChkBox_10mg1 { get; set; }
        public Nullable<bool> ChkBox_15mg1 { get; set; }
        public Nullable<bool> ChkBox_30mg1 { get; set; }
        public string SIG_TxtBox3 { get; set; }
        public string RF_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_cartridge3 { get; set; }
        public Nullable<bool> ChkBox_NutropinAQ { get; set; }
        public Nullable<bool> ChkBox_NuSpinPen { get; set; }
        public Nullable<bool> ChkBox_5mg3 { get; set; }
        public Nullable<bool> ChkBox_10mg2 { get; set; }
        public Nullable<bool> ChkBox_20mg1 { get; set; }
        public Nullable<bool> ChkBox_10mg3 { get; set; }
        public Nullable<bool> ChkBox_20mg2 { get; set; }
        public string SIG_TxtBox4 { get; set; }
        public string RF_TxtBox4 { get; set; }
        public Nullable<bool> ChkBox_Omnitrope { get; set; }
        public Nullable<bool> ChkBox_vial2 { get; set; }
        public Nullable<bool> ChkBox_cartridge4 { get; set; }
        public Nullable<bool> ChkBox_5mg4 { get; set; }
        public Nullable<bool> ChkBox_10mg4 { get; set; }
        public string SIG_TxtBox5 { get; set; }
        public string RF_TxtBox5 { get; set; }
        public Nullable<bool> ChkBox_Saizen { get; set; }
        public Nullable<bool> ChkBox_vial3 { get; set; }
        public Nullable<bool> ChkBox_Click_Easy { get; set; }
        public Nullable<bool> ChkBox_5mg5 { get; set; }
        public Nullable<bool> ChkBox_8_8mg1 { get; set; }
        public string SIG_TxtBox6 { get; set; }
        public string RF_TxtBox6 { get; set; }
        public Nullable<bool> ChkBox_pen_needles { get; set; }
        public Nullable<double> Size_TxtBox { get; set; }
        public string Qty_TxtBox1 { get; set; }
        public Nullable<double> SyringeSize { get; set; }
        public string Qty_TxtBox2 { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public Nullable<bool> ChkBox_Epiphysis { get; set; }
        public Nullable<bool> ChkBox_Syringe { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
