//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormNeurology
    {
        public int RefFormNeurologyId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public Nullable<bool> ChkBox_G35Multiple { get; set; }
        public Nullable<bool> ChkBox_Other { get; set; }
        public string Other_TxtBox { get; set; }
        public Nullable<bool> ChkBox_RelapsingRemitting { get; set; }
        public Nullable<bool> ChkBox_PrimaryProgressive { get; set; }
        public Nullable<bool> ChkBox_SecondaryProgressive { get; set; }
        public Nullable<bool> ChkBox_ProgressiveRelapsing { get; set; }
        public Nullable<bool> ChkBox_patientbeenpreviouslyNo { get; set; }
        public Nullable<bool> ChkBox_patientbeenpreviouslyYes { get; set; }
        public string Medicationfailed_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_patientcurrentlyontherapyNo { get; set; }
        public Nullable<bool> ChkBox_patientcurrentlyontherapyYes { get; set; }
        public string Medicationfailed_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_stoptakingcurrenttherapyYes { get; set; }
        public Nullable<bool> ChkBox_stoptakingcurrenttherapyNo { get; set; }
        public string longwillpatientwaitbeforestarting_TxtBox { get; set; }
        public string othermedicationspatient_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Avonex { get; set; }
        public Nullable<bool> ChkBox_AvonexPFS { get; set; }
        public Nullable<bool> ChkBox_AvonexPEN { get; set; }
        public Nullable<bool> ChkBox_AvonexPwd { get; set; }
        public Nullable<bool> ChkBox_Inject30mcg { get; set; }
        public Nullable<bool> ChkBox_Otherdosing { get; set; }
        public string Otherdosing_TxtBox { get; set; }
        public string Avonex_Qty_TxtBox { get; set; }
        public string Avonex_Refills_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Betaseron { get; set; }
        public Nullable<bool> ChkBox_Betaseron_InitialWeek1and2 { get; set; }
        public Nullable<bool> ChkBox_Betaseron_MaintenanceDose { get; set; }
        public Nullable<bool> ChkBox_Copaxone { get; set; }
        public Nullable<bool> ChkBox_Copaxone_20mg { get; set; }
        public Nullable<bool> ChkBox_Copaxone_40mg { get; set; }
        public Nullable<bool> ChkBox_Copaxone_Inject20mg { get; set; }
        public Nullable<bool> ChkBox_Copaxone_Inject40mg { get; set; }
        public Nullable<bool> ChkBox_Extavia { get; set; }
        public Nullable<bool> ChkBox_ExtaviaInitialWeek1and2 { get; set; }
        public Nullable<bool> ChkBox_ExtaviaInitialMaintenanceDose { get; set; }
        public Nullable<bool> ChkBox_Gilenya { get; set; }
        public Nullable<bool> ChkBox_Glatopa { get; set; }
        public Nullable<bool> ChkBox_Plegridy { get; set; }
        public Nullable<bool> ChkBox_PlegridyStarterPack { get; set; }
        public Nullable<bool> ChkBox_PlegridyPEN { get; set; }
        public Nullable<bool> ChkBox_PlegridyPFS { get; set; }
        public Nullable<bool> ChkBox_Plegridy125mcgPEN { get; set; }
        public Nullable<bool> ChkBox_PlegridyInject63mcg { get; set; }
        public Nullable<bool> ChkBox_PlegridyInject125mcg { get; set; }
        public Nullable<bool> ChkBox_Rebif { get; set; }
        public Nullable<bool> ChkBox_RebifTitrationRebidose { get; set; }
        public Nullable<bool> ChkBox_RebifTitrationPack { get; set; }
        public Nullable<bool> ChkBox_Rebif22mcg_0_5mLRebidose { get; set; }
        public Nullable<bool> ChkBox_Rebif22mcg_0_5mLPFS { get; set; }
        public Nullable<bool> ChkBox_Rebif44mcg_0_5mLRebidose { get; set; }
        public Nullable<bool> ChkBox_Rebif44mcg_0_5mLPFS { get; set; }
        public Nullable<bool> ChkBox_RebifTitrationDose { get; set; }
        public Nullable<bool> ChkBox_RebifMaintenanceDose { get; set; }
        public string Rebif_Inject_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Tecfidera { get; set; }
        public Nullable<bool> ChkBox_TecfideraTitrationStarterPack { get; set; }
        public Nullable<bool> ChkBox_Tecfidera240mg { get; set; }
        public Nullable<bool> ChkBox_Tecfidera120mg { get; set; }
        public Nullable<bool> ChkBox_TecfideraTitrationDose { get; set; }
        public Nullable<bool> ChkBox_TecfideraTake240mg { get; set; }
        public Nullable<bool> ChkBox_TecfideraTake120mg { get; set; }
        public Nullable<bool> ChkBox_TecfideraOther { get; set; }
        public string TecfideraOther_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Epipen { get; set; }
        public string Epipen_REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_EpipenJr { get; set; }
        public Nullable<bool> ChkBox_Others { get; set; }
        public string Others_TxtBox { get; set; }
        public string DrugAllergies_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Plegridy125mcgPFS { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
