//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormRemicade
    {
        public int RefFormRemicadeId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public string CLINICAL_Diagnosis_TxtBox { get; set; }
        public string CLINICAL_ICD_10_TxtBox { get; set; }
        public string CLINICAL_DrugAllergies_TxtBox { get; set; }
        public Nullable<System.DateTime> DATEOFNEXTINFUSION_TxtBox { get; set; }
        public Nullable<double> CURRENTWEIGHT_TxtBox { get; set; }
        public Nullable<bool> ChkBox_5MG_KG { get; set; }
        public Nullable<bool> ChkBox_3MG_KG { get; set; }
        public Nullable<bool> ChkBox_MG_KG { get; set; }
        public string MG_KG_TxtBox { get; set; }
        public Nullable<bool> ChkBox_LOADINGDOSE { get; set; }
        public string ADMINISTER_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_MAINTENANCEDOSE { get; set; }
        public string ADMINISTER_TxtBox2 { get; set; }
        public string MGIVEVERYWEEKS_TxtBox { get; set; }
        public string REFILLS_TxtBox { get; set; }
        public Nullable<bool> ChkBox_MDOFFICE { get; set; }
        public Nullable<bool> ChkBox_INFUSIONCLINIC { get; set; }
        public string Name_TxtBox { get; set; }
        public string Phone_TxtBox { get; set; }
        public Nullable<bool> ChkBox_HOMEINFUSION { get; set; }
        public string HOMEHEALTHAGENCY_TxtBox { get; set; }
        public string Phone_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_KROGERSPECIALTY { get; set; }
        public Nullable<bool> ChkBox_INFUSIONSUPPLIES { get; set; }
        public Nullable<bool> ChkBox_ACETAMINOPHEN { get; set; }
        public Nullable<bool> ChkBox_DIPHENHYDRAMINE { get; set; }
        public Nullable<bool> ChkBox_DIPHENHYDRAMINE2 { get; set; }
        public Nullable<bool> ChkBox_PREDNISONE { get; set; }
        public Nullable<bool> ChkBox_SOLUMEDROL { get; set; }
        public Nullable<bool> CheckBox_1 { get; set; }
        public string TextBox1 { get; set; }
        public string Qty_TxtBox1 { get; set; }
        public string Qty_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_SOLUMEDROL2 { get; set; }
        public string Qty_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_PHENERGAN { get; set; }
        public Nullable<bool> ChkBox_25MG { get; set; }
        public Nullable<bool> ChkBox_PO { get; set; }
        public Nullable<bool> ChkBox_IVP { get; set; }
        public string Qty_TxtBox4 { get; set; }
        public Nullable<bool> CheckBox_2 { get; set; }
        public string TextBox2 { get; set; }
        public string Qty_TxtBox5 { get; set; }
        public Nullable<bool> ChkBox_PERIPHERALACCESS { get; set; }
        public Nullable<bool> ChkBox_CENTRALVENOUSACCESS { get; set; }
        public Nullable<bool> ChkBox_HEPARINFLUSH { get; set; }
        public string HEPARINFLUSH_Qty_TxtBox { get; set; }
        public Nullable<bool> ChkBox_HEPARINFLUSH2 { get; set; }
        public string HEPARINFLUSH_Qty_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_SALINEFLUSH { get; set; }
        public string SALINEFLUSH_Qty_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Empty { get; set; }
        public string TxtBox_Empty { get; set; }
        public string TxtBox_Empty_Qty { get; set; }
        public Nullable<bool> ChkBox_EPINEPHRINE { get; set; }
        public string EPINEPHRINE_TxtBox { get; set; }
        public Nullable<bool> ChkBox1_SIG { get; set; }
        public string SIG_TxtBox1 { get; set; }
        public string SIG_Qty_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox2_SIG { get; set; }
        public string SIG_TxtBox2 { get; set; }
        public string SIG_Qty_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox3_SIG { get; set; }
        public string SIG_TxtBox3 { get; set; }
        public string SIG_Qty_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_SIG { get; set; }
        public Nullable<bool> ChkBox_MAINTENANCEDOSE2 { get; set; }
        public string REF_PRN_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Others { get; set; }
        public string Others_TxtBox { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
