//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormPediatricGastoenterology
    {
        public int RefFormPediatricgatroenterologyId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_ShipToPatient { get; set; }
        public Nullable<bool> ChkBox_ShipToOffice { get; set; }
        public Nullable<bool> ChkBox_ShipToOther { get; set; }
        public string TxtBox_ShipToOther { get; set; }
        public Nullable<bool> ChkBox_CLINICAL_Pediatric555_9 { get; set; }
        public Nullable<bool> ChkBox_CLINICAL_Pediatric556_0 { get; set; }
        public string CLINICAL_DrugAllergies_TxtBox { get; set; }
        public string CLINICAL_Prior_TxtBox1 { get; set; }
        public string CLINICAL_LengthofTreatment_TxtBox1 { get; set; }
        public string CLINICAL_ReasonforDiscontinuing_TxtBox1 { get; set; }
        public string CLINICAL_Prior_TxtBox2 { get; set; }
        public string CLINICAL_LengthofTreatment_TxtBox2 { get; set; }
        public string CLINICAL_ReasonforDiscontinuing_TxtBox2 { get; set; }
        public string CLINICAL_Prior_TxtBox3 { get; set; }
        public string CLINICAL_LengthofTreatment_TxtBox3 { get; set; }
        public string CLINICAL_ReasonforDiscontinuing_TxtBox3 { get; set; }
        public Nullable<double> CLINICAL_Patient_Weight_TxtBox { get; set; }
        public Nullable<bool> ChkBox_latexallergy_Yes { get; set; }
        public Nullable<bool> ChkBox_latexallergy_No { get; set; }
        public Nullable<bool> ChkBox_beforestart_Yes { get; set; }
        public Nullable<bool> ChkBox_beforestart_No { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Humira { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_PediatricCrohnsDisease1 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_LoadDay1 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Maintenancebegins1 { get; set; }
        public string PRESCRIPTION_REFILLS_TxtBox1 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_PediatricCrohnsDisease2 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_LoadDay2 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_four40mginjections { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_two40mg { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Maintenancebegins2 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_CrohnsStarterPackage { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_20mgPreFilledSyringe { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_40mgPreFilledSyringe { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_40mgPreFilledPen { get; set; }
        public string PRESCRIPTION_REFILLS_TxtBox2 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Remicade { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_100mgoflyophilized { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_LoadDay3 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Maintenancebegins3 { get; set; }
        public string PRESCRIPTION_REFILLS_TxtBox3 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_LoadDay4 { get; set; }
        public Nullable<bool> ChkBox_PRESCRIPTION_Maintenancebegins4 { get; set; }
        public string PRESCRIPTION_REFILLS_TxtBox4 { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
