//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFormTransplant1
    {
        public int RefFormTransplantId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> FormNeedsByDate { get; set; }
        public Nullable<bool> ChkBox_Z94_0KidneyTransplant { get; set; }
        public Nullable<bool> ChkBox_Z94_1HeartTransplant { get; set; }
        public Nullable<bool> ChkBox_Other { get; set; }
        public string Other_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Demographics { get; set; }
        public Nullable<bool> ChkBox_HandP { get; set; }
        public Nullable<bool> ChkBox_PhysicianOrders { get; set; }
        public Nullable<bool> ChkBox_InsuranceInformation { get; set; }
        public Nullable<bool> ChkBox_Labs { get; set; }
        public string Diphenhydramine_TxtBox { get; set; }
        public string Acetaminophen_TxtBox { get; set; }
        public string Prednisone_TxtBox { get; set; }
        public string OtherMeds_TxtBox { get; set; }
        public string InfuseIVIG_TxtBox { get; set; }
        public string gramsor_TxtBox { get; set; }
        public string gm_kgIVover_TxtBox { get; set; }
        public string Frequency_TxtBox { get; set; }
        public string Duration_TxtBox { get; set; }
        public Nullable<bool> ChkBox_PharmacytoSelect { get; set; }
        public Nullable<bool> ChkBox_NoIVIGRequested { get; set; }
        public Nullable<bool> ChkBox_patientisgreater { get; set; }
        public Nullable<bool> ChkBox_patientisless { get; set; }
        public string patientisgreater_TxtBox { get; set; }
        public string patientisless_TxtBox { get; set; }
        public Nullable<double> Hours_TxtBox { get; set; }
        public Nullable<bool> ChkBox_Over { get; set; }
        public Nullable<bool> ChkBox_Initialrateof50mg_hr { get; set; }
        public Nullable<bool> ChkBox_NormalSaline { get; set; }
        public Nullable<bool> ChkBox_D5W { get; set; }
        public Nullable<bool> ChkBox_1mg_ml { get; set; }
        public Nullable<bool> ChkBox_2mg_ml { get; set; }
        public Nullable<bool> ChkBox_4mg_ml { get; set; }
        public Nullable<bool> ChkBox_NoRituxanRequested { get; set; }
        public Nullable<bool> ChkBox_BUN { get; set; }
        public Nullable<bool> ChkBox_Priortofirstinfusion1 { get; set; }
        public Nullable<bool> ChkBox_After1 { get; set; }
        public Nullable<bool> ChkBox_Others { get; set; }
        public Nullable<bool> ChkBox_Priortofirstinfusion2 { get; set; }
        public Nullable<bool> ChkBox_After2 { get; set; }
        public string PhysicianName_TxtBox { get; set; }
        public string License_TxtBox { get; set; }
        public string Address_TxtBox { get; set; }
        public string DEA_TxtBox { get; set; }
        public string City_TxtBox { get; set; }
        public string NPI_TxtBox { get; set; }
        public string Phone_TxtBox { get; set; }
        public string Fax_TxtBox { get; set; }
        public string OfficeContact_TxtBox { get; set; }
        public Nullable<bool> ChkBox_LungTransplant { get; set; }
        public string Others_TxtBox { get; set; }
        public string After_TxtBox1 { get; set; }
        public string After_TxtBox2 { get; set; }
        public string ZIP_TxtBox { get; set; }
        public string State_TxtBox { get; set; }
        public Nullable<bool> ChkBox_V42_0KidneyTransplant { get; set; }
        public Nullable<bool> ChkBox_V42_1HeartTransplant { get; set; }
        public Nullable<bool> ChkBox_V42_6LungTransplant { get; set; }
        public Nullable<bool> IsSignatured { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
