//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefillFaxReportLog
    {
        public int RefillFaxReportLogId { get; set; }
        public Nullable<int> patientid { get; set; }
        public string PatientName { get; set; }
        public string PhysName { get; set; }
        public string PhysAddress { get; set; }
        public string physphone { get; set; }
        public string physno { get; set; }
        public string physnpi { get; set; }
        public string physFaxNo { get; set; }
        public string RXNum { get; set; }
        public string Drug { get; set; }
        public Nullable<System.DateTime> entstatuschanged { get; set; }
        public Nullable<int> cfk_pnnames_entstatus { get; set; }
        public Nullable<int> cfk_popupdata_entstatus_lastevent { get; set; }
        public string HTMLText { get; set; }
        public Nullable<int> SentStatus { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ReportType { get; set; }
        public Nullable<int> RXNumCount { get; set; }
        public Nullable<int> SiteNo { get; set; }
        public Nullable<System.DateTime> NextFillDate { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> PharmacyId { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<int> SentBy { get; set; }
        public Nullable<int> RefillStatusId { get; set; }
        public string RefillDocumentPath { get; set; }
        public string RefillDocumentName { get; set; }
        public Nullable<bool> StatusChanged { get; set; }
    
        public virtual RefillStatu RefillStatu { get; set; }
    }
}
