//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDocument
    {
        public int DocumentId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public int PhysicianId { get; set; }
        public string FolderFileName { get; set; }
        public string FolderFileNameUNC { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string PatientFullName { get; set; }
        public string PhysicianFullName { get; set; }
        public string NationalProviderIdentifier { get; set; }
        public string DocumentName { get; set; }
    }
}
