//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLastThreadMessage
    {
        public int ThreadId { get; set; }
        public int MessageId { get; set; }
        public string PatientName { get; set; }
        public string PhysicianName { get; set; }
        public string LastMessage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> ThreadCount { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    }
}
