//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwNotificationAlert
    {
        public string AlertButtonMessage { get; set; }
        public string AlertMessage { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public long NID { get; set; }
        public string Url { get; set; }
        public string AlertMessageSubject { get; set; }
        public int ItemId { get; set; }
        public string ClassName { get; set; }
    }
}
