//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPhysicianNote
    {
        public int PhysicianNoteId { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string PhysicianNote { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> EmailSend { get; set; }
        public Nullable<bool> FaxSend { get; set; }
        public Nullable<bool> PharmacySend { get; set; }
        public string FullName { get; set; }
        public string PhysicianName { get; set; }
        public string OriginatingPharmacy { get; set; }
        public string PatientCode { get; set; }
    }
}
