//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPrescription
    {
        public int PrescriptionId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public int PhysicianId { get; set; }
        public int RefillsAllowed { get; set; }
        public int RefillNumber { get; set; }
        public Nullable<int> RefillsRemaining { get; set; }
        public Nullable<int> DaysSupplied { get; set; }
        public Nullable<System.DateTime> FillDate { get; set; }
        public Nullable<System.DateTime> DoseStartDate { get; set; }
        public Nullable<System.DateTime> NextFillDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string RxNumber { get; set; }
        public Nullable<System.DateTime> RxDate { get; set; }
        public string OrderItemName { get; set; }
    }
}
