//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReferralDocument
    {
        public int PhysicianPortalPatientChecklistRelationshipId { get; set; }
        public Nullable<int> PhysicianPortalPatientId { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string PatientFullName { get; set; }
        public string PhysicianFullName { get; set; }
        public string NationalProviderIdentifier { get; set; }
        public string FileName { get; set; }
        public int RefferalFormDocumentId { get; set; }
    }
}
