//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRefillFaxReportLog
    {
        public int PhysicianId { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalProviderIdentifier { get; set; }
        public string FaxNumber { get; set; }
        public string CompanyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string StateProvince { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string RXNum { get; set; }
        public string PatientName { get; set; }
        public string Drug { get; set; }
        public string HTMLText { get; set; }
        public Nullable<int> SentStatus { get; set; }
        public Nullable<int> RXNumCount { get; set; }
        public int id { get; set; }
        public Nullable<int> PharmacyId { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public string PharmacyFaxNumber { get; set; }
        public string SentBy { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public string RefillStatus { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string RefillDocumentPath { get; set; }
        public int NotesCount { get; set; }
    }
}
