//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRefillFaxDocument
    {
        public int PhysicianId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string PhysicianFullName { get; set; }
        public string NPI { get; set; }
        public string PatientName { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public string SentBy { get; set; }
        public string RefillDocumentPath { get; set; }
        public string RefillDocumentName { get; set; }
    }
}
