//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianPortal.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWorkflow
    {
        public Nullable<System.DateTime> WorkflowStartDateId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public Nullable<int> PhysicianMasterId { get; set; }
        public Nullable<int> SalesTeamId { get; set; }
        public int OperationsWorkflowId { get; set; }
        public string WorkflowName { get; set; }
        public string WorkflowSourceEntity { get; set; }
        public Nullable<int> PrescriptionId { get; set; }
        public string OrderItemName { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<long> PatientPrescriptionOperationsWorkflowCounterId { get; set; }
        public string colorcode { get; set; }
    }
}
