//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTeam.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProcessTime
    {
        public int DimProcessTimesId { get; set; }
        public Nullable<System.DateTime> LatestOrderTime { get; set; }
        public Nullable<System.DateTime> LatestDeliveryTime { get; set; }
        public Nullable<System.DateTime> LatestNotesTime { get; set; }
        public Nullable<System.DateTime> LatestPaymentTime { get; set; }
        public Nullable<System.DateTime> LatestDocumentTime { get; set; }
    }
}
