//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTeam.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianConsent
    {
        public int PhysicianConsentId { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public Nullable<int> SalesTeamId { get; set; }
        public Nullable<bool> ConsentGranted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string IPAdressSalesTeam { get; set; }
        public string PhysicianEmailAddress { get; set; }
        public Nullable<System.DateTime> ConsentChangedOn { get; set; }
    }
}
