//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTeam.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPortalFaxLog
    {
        public int FaxLogId { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public string SentTo { get; set; }
        public Nullable<int> SentToPhysicianId { get; set; }
        public string Status { get; set; }
        public string ErrorMessage { get; set; }
    }
}
