//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTeam.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDocument
    {
        public int DocumenstId { get; set; }
        public int PatientId { get; set; }
        public int PhysicianId { get; set; }
        public Nullable<long> SalesId { get; set; }
        public Nullable<int> SalesTeamId { get; set; }
        public string PharmacyName { get; set; }
        public string FolderFileNameUNC { get; set; }
        public string DocumentType { get; set; }
        public string DocumentDescription { get; set; }
        public string DocumentStatus { get; set; }
        public Nullable<System.DateTime> DocumentCreatedDate { get; set; }
        public Nullable<System.DateTime> DocumentAssignedDate { get; set; }
        public Nullable<int> DocumentCreatedTimeId { get; set; }
        public Nullable<int> DocumentAssignedTimeId { get; set; }
        public Nullable<int> DeliveryDrugId { get; set; }
        public Nullable<int> ReferralPharmacyId { get; set; }
        public Nullable<int> DiseaseStateId { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> PrimaryInsuranceId { get; set; }
        public Nullable<int> SecondaryInsuranceId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> PrescriptionId { get; set; }
        public Nullable<int> DispensingPharmacyId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> DrugTherapyGroupId { get; set; }
        public Nullable<System.DateTime> PatientReferralDate { get; set; }
        public Nullable<System.DateTime> PatientDrugReferralDate { get; set; }
        public Nullable<System.DateTime> PatientFirstShipDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> DeliveryAddressId { get; set; }
        public Nullable<System.DateTime> OrderReviewedDate { get; set; }
        public Nullable<System.DateTime> PackagedDate { get; set; }
        public Nullable<int> TherapyPatientStatusId { get; set; }
        public Nullable<int> DrugPatientStatusId { get; set; }
    }
}
