//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTeam.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPrescription
    {
        public int PrescriptionId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public int PhysicianId { get; set; }
        public string RxNumber { get; set; }
        public Nullable<int> FillNumber { get; set; }
        public Nullable<int> FillsAllowed { get; set; }
        public Nullable<int> FillsRemaining { get; set; }
        public string OrderItemName { get; set; }
        public Nullable<System.DateTime> RxDate { get; set; }
        public Nullable<int> DaysSupplied { get; set; }
        public string OrderStatus { get; set; }
        public string LastOrderEvent { get; set; }
        public Nullable<int> DaysSupplyPrescribed { get; set; }
        public Nullable<int> DaysSuppliedFilledToDate { get; set; }
        public Nullable<decimal> MedicationTherapyCompletionPercent { get; set; }
        public string TherapyStatusWeeks { get; set; }
        public string TherapyStatus { get; set; }
        public string ICD10 { get; set; }
        public string ICD10Description { get; set; }
        public string LastFillIndicator { get; set; }
    }
}
