//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTeam.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSalesTeam
    {
        public int SalesTeamId { get; set; }
        public string SalesRepresentativeFirstName { get; set; }
        public string SalesRepresentativeLastName { get; set; }
        public string SalesRepresentativeFullName { get; set; }
        public string SalesTerritory { get; set; }
        public string ParentSaleTeamFullName { get; set; }
        public Nullable<int> ParentSalesTeamId { get; set; }
        public string SalesRegion { get; set; }
        public string ADUserName { get; set; }
    }
}
